# Generated by Django 5.0 on 2023-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ccode', models.BigIntegerField()),
            ],
        ),
    ]
